package org.example
 
import org.example.Person;

rule "高額商品"
    when
        $p : Person( age >= 12 )
        $o : Order( consumer == $p, itemPrice > 100000 )
    then
        System.out.println( $p.getName() + "さん、 " + $o.toString() + " の注文をご確認ください");
end

rule "高額商品 子ども"
    when
        $p : Person( age < 12 )
        $o : Order( consumer == $p, itemPrice > 5000 )
    then
        System.out.println( $p.getName() + "さん、 " + $o.toString() + " の注文を保護者とご確認ください");
end
